# This file is auto-generated by tools/gen_core_stub.py — do not edit manually.
from collections.abc import Sequence
from typing import Any

from pandas import DataFrame, Series

class AnalysisIndicators:
    # candles
    def cdl_doji(
        self,
        length: int | None = None,
        factor: float | None = None,
        scalar: float | None = None,
        asint: bool = True,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def cdl_inside(self, asbool: bool = False, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def cdl_pattern(
        self, name: str | Sequence[str] = 'all', scalar: float | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def cdl_z(
        self, length: int | None = None, full: bool | None = None, ddof: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def ha(self, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...

    # cycles
    def dsp(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ebsw(self, length: int | None = None, bars: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ht_dcperiod(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ht_dcphase(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ht_phasor(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def ht_sine(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def ht_trendmode(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def msw(self, period: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...

    # math
    def acos(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def add(self, series_a: Series, series_b: Series, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def asin(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def atan(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ceil(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def cos(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def cosh(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def div(self, series_a: Series, series_b: Series, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def exp(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def floor(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ln(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def log10(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def maxindex(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def minindex(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def minmax(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def minmaxindex(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def mult(self, series_a: Series, series_b: Series, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def npabs(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def npround(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def rolling_max(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def rolling_min(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def rolling_sum(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def sin(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def sinh(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def sqrt(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def sub(self, series_a: Series, series_b: Series, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def tan(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def tanh(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def todeg(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def torad(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def trunc(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...

    # momentum
    def ao(self, fast: int | None = None, slow: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def apo(
        self,
        fast: int | None = None,
        slow: int | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def bias(self, length: int | None = None, mamode: str | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def bop(self, scalar: float | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def brar(
        self, length: int | None = None, scalar: float | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def cci(
        self, length: int | None = None, c: float | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def cfo(
        self, length: int | None = None, scalar: float | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def cg(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def cmo(
        self,
        length: int | None = None,
        scalar: float | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def coppock(
        self, length: int | None = None, fast: int | None = None, slow: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def cti(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def dm(
        self,
        length: int | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def er(self, length: int | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | DataFrame | None: ...
    def eri(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def fisher(self, length: int | None = None, signal: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def fosc(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def inertia(
        self,
        length: int | None = None,
        rvi_length: int | None = None,
        scalar: float | None = None,
        refined: bool | None = None,
        thirds: bool | None = None,
        mamode: str | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def kdj(self, length: int | None = None, signal: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def kst(
        self,
        roc1: int | None = None,
        roc2: int | None = None,
        roc3: int | None = None,
        roc4: int | None = None,
        sma1: int | None = None,
        sma2: int | None = None,
        sma3: int | None = None,
        sma4: int | None = None,
        signal: int | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def lrsi(self, length: int | None = None, gamma: float | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def macd(
        self,
        fast: int | None = None,
        slow: int | None = None,
        signal: int | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def macdext(
        self,
        fast: int | None = None,
        slow: int | None = None,
        signal: int | None = None,
        fastmatype: int | None = None,
        slowmatype: int | None = None,
        signalmatype: int | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def macdfix(self, signal: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def mom(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def pgo(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def po(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ppo(
        self,
        fast: int | None = None,
        slow: int | None = None,
        signal: int | None = None,
        scalar: float | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def psl(
        self, length: int | None = None, scalar: float | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def pvo(
        self,
        fast: int | None = None,
        slow: int | None = None,
        signal: int | None = None,
        scalar: float | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def qqe(
        self,
        length: int | None = None,
        smooth: int | None = None,
        factor: float | None = None,
        mamode: str | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def roc(
        self, length: int | None = None, scalar: float | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def rocp(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def rocr(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def rocr100(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def rsi(
        self,
        length: int | None = None,
        scalar: float | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | DataFrame | None: ...
    def rsx(self, length: int | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | DataFrame | None: ...
    def rvgi(self, length: int | None = None, swma_length: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def slope(
        self,
        length: int | None = None,
        as_angle: bool | None = None,
        to_degrees: bool | None = None,
        vertical: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def smc_sweep(self, length: int | None = None, wick_mult: float | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def smi(
        self,
        fast: int | None = None,
        slow: int | None = None,
        signal: int | None = None,
        scalar: float | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def squeeze(
        self,
        bb_length: int | None = None,
        bb_std: float | None = None,
        kc_length: int | None = None,
        kc_scalar: float | None = None,
        mom_length: int | None = None,
        mom_smooth: int | None = None,
        use_tr: bool | None = None,
        mamode: str | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def squeeze_pro(
        self,
        bb_length: int | None = None,
        bb_std: float | None = None,
        kc_length: int | None = None,
        kc_scalar_wide: float | None = None,
        kc_scalar_normal: float | None = None,
        kc_scalar_narrow: float | None = None,
        mom_length: int | None = None,
        mom_smooth: int | None = None,
        use_tr: bool | None = None,
        mamode: str | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def stc(
        self,
        tclength: int | None = None,
        fast: int | None = None,
        slow: int | None = None,
        factor: float | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def stoch(
        self,
        k: int | None = None,
        d: int | None = None,
        smooth_k: int | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def stochf(
        self,
        fastk: int | None = None,
        fastd: int | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def stochrsi(
        self,
        length: int | None = None,
        rsi_length: int | None = None,
        k: int | None = None,
        d: int | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def td_seq(self, asint: bool | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def trix(
        self,
        length: int | None = None,
        signal: int | None = None,
        scalar: float | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def trixh(
        self,
        length: int | None = None,
        signal: int | None = None,
        scalar: float | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def tsi(
        self,
        fast: int | None = None,
        slow: int | None = None,
        signal: int | None = None,
        scalar: float | None = None,
        mamode: str | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def uo(
        self,
        fast: int | None = None,
        medium: int | None = None,
        slow: int | None = None,
        fast_w: float | None = None,
        medium_w: float | None = None,
        slow_w: float | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def vwmacd(
        self, fast: int | None = None, slow: int | None = None, signal: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def willr(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...

    # overlap
    def alma(
        self,
        length: int | None = None,
        sigma: float | None = None,
        distribution_offset: float | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def avgprice(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def dema(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ema(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def fwma(self, length: int | None = None, asc: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def hilo(
        self, high_length: int | None = None, low_length: int | None = None, mamode: str | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def hl2(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def hlc3(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def hma(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ht_trendline(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def hwma(
        self, na: float | None = None, nb: float | None = None, nc: float | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def ichimoku(
        self,
        tenkan: int | None = None,
        kijun: int | None = None,
        senkou: int | None = None,
        include_chikou: bool = True,
        offset: int | None = None,
        append_span: bool = False,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def jma(self, length: float | None = None, phase: float | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def kama(
        self,
        length: int | None = None,
        fast: int | None = None,
        slow: int | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def linreg(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def linregangle(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def linregintercept(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def linregslope(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ma(self, name: str | None = None, source: Series | None = None, **kwargs: Any) -> Series | None: ...
    def mama(
        self, fastlimit: float | None = None, slowlimit: float | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def mavp(
        self,
        periods: Series | None = None,
        minperiod: int | None = None,
        maxperiod: int | None = None,
        mamode: int | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def mcgd(self, length: int | None = None, offset: int | None = None, c: float | None = None, **kwargs: Any) -> Series | None: ...
    def medprice(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def midpoint(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def midprice(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def mmar(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def ohlc4(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def pwma(self, length: int | None = None, asc: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def rainbow(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def rma(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def sinwma(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def sma(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ssf(self, length: int | None = None, poles: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def supertrend(
        self, length: int | None = None, multiplier: float | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def swma(self, length: int | None = None, asc: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def t3(
        self, length: int | None = None, a: float | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def tema(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def trima(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def tsf(self, length: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def typprice(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def vidya(self, length: int | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def vwap(self, anchor: str | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def vwma(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def wcp(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def wma(
        self, length: int | None = None, asc: bool | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def zlma(self, length: int | None = None, mamode: str | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...

    # performance
    def drawdown(self, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def log_return(self, length: int | None = None, cumulative: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def percent_return(
        self, length: int | None = None, cumulative: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...

    # statistics
    def beta(self, benchmark: Series | None = None, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def correl(self, benchmark: Series | None = None, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def entropy(self, length: int | None = None, base: float | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def kurtosis(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def mad(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def md(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def median(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def quantile(self, length: int | None = None, q: float | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def skew(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def stderr(self, length: int | None = None, ddof: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def stdev(
        self, length: int | None = None, ddof: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def tos_stdevall(
        self, length: int | None = None, stds: list[int] | None = None, ddof: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def variance(
        self, length: int | None = None, ddof: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def zscore(self, length: int | None = None, std: float | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...

    # trend
    def adx(
        self,
        length: int | None = None,
        lensig: int | None = None,
        scalar: float | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def adxr(
        self,
        length: int | None = None,
        lensig: int | None = None,
        scalar: float | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def amat(
        self,
        fast: int | None = None,
        slow: int | None = None,
        lookback: int | None = None,
        mamode: str | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def aroon(
        self, length: int | None = None, scalar: float | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def chop(
        self,
        length: int | None = None,
        atr_length: int | None = None,
        ln: bool | None = None,
        scalar: float | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def cksp(
        self, p: int | None = None, x: float | None = None, q: int | None = None, tvmode: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def cpr(
        self,
        method: str = 'classic',
        timeframe: str = 'daily',
        interval: str | None = None,
        levels: str = 'standard',
        width_analysis: bool = True,
        price_position: bool = True,
        virgin_cpr: bool = False,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def decay(
        self, kind: str | None = None, length: int | None = None, mode: str | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def decreasing(
        self,
        length: int | None = None,
        strict: bool | None = None,
        asint: bool | None = None,
        percent: float | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def dpo(self, length: int | None = None, centered: bool = True, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def dx(
        self,
        length: int | None = None,
        scalar: float | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def edecay(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def increasing(
        self,
        length: int | None = None,
        strict: bool | None = None,
        asint: bool | None = None,
        percent: float | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def long_run(self, fast: Series, slow: Series, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def minus_dm(
        self, length: int | None = None, talib: bool | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def plus_dm(
        self, length: int | None = None, talib: bool | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def pmax(
        self, length: int | None = None, multiplier: float | None = None, mamode: str | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def psar(
        self,
        af0: float | None = None,
        af: float | None = None,
        max_af: float | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def qstick(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def sarext(
        self,
        startvalue: float | None = None,
        offsetonreverse: float | None = None,
        accelerationinitlong: float | None = None,
        accelerationlong: float | None = None,
        accelerationmaxlong: float | None = None,
        accelerationinitshort: float | None = None,
        accelerationshort: float | None = None,
        accelerationmaxshort: float | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def short_run(self, fast: Series, slow: Series, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def tsignals(
        self,
        trend: Series,
        asbool: bool | None = None,
        trend_reset: int = 0,
        trade_offset: int | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def ttm_trend(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def vhf(self, length: int | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def vortex(self, length: int | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def xsignals(
        self,
        signal: Series,
        xa: float,
        xb: float,
        above: bool = True,
        long: bool = True,
        asbool: bool | None = None,
        trend_reset: int = 0,
        trade_offset: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...

    # volatility
    def aberration(self, length: int | None = None, atr_length: int | None = None, offset: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def accbands(
        self,
        length: int | None = None,
        c: float | None = None,
        drift: int | None = None,
        mamode: str | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def atr(
        self,
        length: int | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def avolume(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def bbands(
        self,
        length: int | None = None,
        std: float | None = None,
        ddof: int = 0,
        mamode: str | None = None,
        talib: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def ce(
        self, length: int | None = None, multiplier: float | None = None, mamode: str | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def cvi(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def donchian(
        self, lower_length: int | None = None, upper_length: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def hvol(self, length: int | None = None, annualization: float | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def hwc(
        self,
        na: float | None = None,
        nb: float | None = None,
        nc: float | None = None,
        nd: float | None = None,
        scalar: float | None = None,
        channel_eval: bool | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def kc(
        self, length: int | None = None, scalar: float | None = None, mamode: str | None = None, offset: int | None = None, **kwargs: Any
    ) -> DataFrame | None: ...
    def massi(self, fast: int | None = None, slow: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def natr(
        self,
        length: int | None = None,
        scalar: float | None = None,
        mamode: str | None = None,
        talib: bool | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def pdist(self, drift: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def rvi(
        self,
        length: int | None = None,
        scalar: float | None = None,
        refined: bool | None = None,
        thirds: bool | None = None,
        mamode: str | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def thermo(
        self,
        length: int | None = None,
        long: float | None = None,
        short: float | None = None,
        mamode: str | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def true_range(self, talib: bool | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def ui(self, length: int | None = None, scalar: float | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...

    # volume
    def ad(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def adosc(
        self, fast: int | None = None, slow: int | None = None, talib: bool | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def aobv(
        self,
        fast: int | None = None,
        slow: int | None = None,
        max_lookback: int | None = None,
        min_lookback: int | None = None,
        mamode: str | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def cmf(self, length: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def efi(
        self, length: int | None = None, mamode: str | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def emv(self, drift: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def eom(
        self, length: int | None = None, divisor: float | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def kvo(
        self,
        fast: int | None = None,
        slow: int | None = None,
        signal: int | None = None,
        mamode: str | None = None,
        drift: int | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> DataFrame | None: ...
    def marketfi(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def mfi(
        self, length: int | None = None, talib: bool | None = None, drift: int | None = None, offset: int | None = None, **kwargs: Any
    ) -> Series | None: ...
    def nvi(self, length: int | None = None, initial: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def obv(self, talib: bool | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def pvi(self, length: int | None = None, initial: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def pvol(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def pvr(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def pvt(self, drift: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def vfi(
        self,
        length: int | None = None,
        coef: float | None = None,
        vcoef: float | None = None,
        mamode: str | None = None,
        offset: int | None = None,
        **kwargs: Any,
    ) -> Series | None: ...
    def vosc(self, fast: int | None = None, slow: int | None = None, offset: int | None = None, **kwargs: Any) -> Series | None: ...
    def vp(self, width: int | None = None, **kwargs: Any) -> DataFrame | None: ...
    def wad(self, offset: int | None = None, **kwargs: Any) -> Series | None: ...
