# This file is auto-generated by tools/gen_core_stub.py — do not edit manually.
from typing import Any, Optional, Sequence, Union
from pandas import Series, DataFrame

class AnalysisIndicators:
    # candles
    def cdl_doji(
        self,
        length: Optional[int] = None,
        factor: Optional[float] = None,
        scalar: Optional[float] = None,
        asint: bool = True,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def cdl_inside(self, asbool: bool = False, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def cdl_pattern(
        self, name: Union[str, Sequence[str]] = 'all', scalar: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def cdl_z(
        self, length: Optional[int] = None, full: Optional[bool] = None, ddof: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def ha(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...

    # cycles
    def dsp(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ebsw(self, length: Optional[int] = None, bars: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ht_dcperiod(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ht_dcphase(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ht_phasor(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def ht_sine(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def ht_trendmode(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def msw(self, period: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...

    # math
    def acos(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def add(self, series_a: Series, series_b: Series, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def asin(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def atan(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ceil(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def cos(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def cosh(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def div(self, series_a: Series, series_b: Series, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def exp(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def floor(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ln(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def log10(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def maxindex(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def minindex(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def minmax(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def minmaxindex(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def mult(self, series_a: Series, series_b: Series, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def npabs(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def npround(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def rolling_max(
        self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def rolling_min(
        self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def rolling_sum(
        self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def sin(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def sinh(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def sqrt(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def sub(self, series_a: Series, series_b: Series, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def tan(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def tanh(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def todeg(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def torad(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def trunc(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...

    # momentum
    def ao(self, fast: Optional[int] = None, slow: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def apo(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def bias(self, length: Optional[int] = None, mamode: Optional[str] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def bop(self, scalar: Optional[float] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def brar(
        self, length: Optional[int] = None, scalar: Optional[float] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def cci(
        self, length: Optional[int] = None, c: Optional[float] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def cfo(
        self, length: Optional[int] = None, scalar: Optional[float] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def cg(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def cmo(
        self,
        length: Optional[int] = None,
        scalar: Optional[float] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def coppock(
        self, length: Optional[int] = None, fast: Optional[int] = None, slow: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def cti(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def dm(
        self,
        length: Optional[int] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def er(
        self, length: Optional[int] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Union[Series, DataFrame]]: ...
    def eri(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def fisher(
        self, length: Optional[int] = None, signal: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def fosc(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def inertia(
        self,
        length: Optional[int] = None,
        rvi_length: Optional[int] = None,
        scalar: Optional[float] = None,
        refined: Optional[bool] = None,
        thirds: Optional[bool] = None,
        mamode: Optional[str] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def kdj(self, length: Optional[int] = None, signal: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def kst(
        self,
        roc1: Optional[int] = None,
        roc2: Optional[int] = None,
        roc3: Optional[int] = None,
        roc4: Optional[int] = None,
        sma1: Optional[int] = None,
        sma2: Optional[int] = None,
        sma3: Optional[int] = None,
        sma4: Optional[int] = None,
        signal: Optional[int] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def lrsi(self, length: Optional[int] = None, gamma: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def macd(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        signal: Optional[int] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def macdext(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        signal: Optional[int] = None,
        fastmatype: Optional[int] = None,
        slowmatype: Optional[int] = None,
        signalmatype: Optional[int] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def macdfix(
        self, signal: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def mom(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def pgo(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def po(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ppo(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        signal: Optional[int] = None,
        scalar: Optional[float] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def psl(
        self, length: Optional[int] = None, scalar: Optional[float] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def pvo(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        signal: Optional[int] = None,
        scalar: Optional[float] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def qqe(
        self,
        length: Optional[int] = None,
        smooth: Optional[int] = None,
        factor: Optional[float] = None,
        mamode: Optional[str] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def roc(
        self, length: Optional[int] = None, scalar: Optional[float] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def rocp(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def rocr(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def rocr100(
        self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def rsi(
        self,
        length: Optional[int] = None,
        scalar: Optional[float] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Union[Series, DataFrame]]: ...
    def rsx(
        self, length: Optional[int] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Union[Series, DataFrame]]: ...
    def rvgi(
        self, length: Optional[int] = None, swma_length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def slope(
        self,
        length: Optional[int] = None,
        as_angle: Optional[bool] = None,
        to_degrees: Optional[bool] = None,
        vertical: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def smc_sweep(
        self, length: Optional[int] = None, wick_mult: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def smi(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        signal: Optional[int] = None,
        scalar: Optional[float] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def squeeze(
        self,
        bb_length: Optional[int] = None,
        bb_std: Optional[float] = None,
        kc_length: Optional[int] = None,
        kc_scalar: Optional[float] = None,
        mom_length: Optional[int] = None,
        mom_smooth: Optional[int] = None,
        use_tr: Optional[bool] = None,
        mamode: Optional[str] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def squeeze_pro(
        self,
        bb_length: Optional[int] = None,
        bb_std: Optional[float] = None,
        kc_length: Optional[int] = None,
        kc_scalar_wide: Optional[float] = None,
        kc_scalar_normal: Optional[float] = None,
        kc_scalar_narrow: Optional[float] = None,
        mom_length: Optional[int] = None,
        mom_smooth: Optional[int] = None,
        use_tr: Optional[bool] = None,
        mamode: Optional[str] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def stc(
        self,
        tclength: Optional[int] = None,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        factor: Optional[float] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def stoch(
        self,
        k: Optional[int] = None,
        d: Optional[int] = None,
        smooth_k: Optional[int] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def stochf(
        self,
        fastk: Optional[int] = None,
        fastd: Optional[int] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def stochrsi(
        self,
        length: Optional[int] = None,
        rsi_length: Optional[int] = None,
        k: Optional[int] = None,
        d: Optional[int] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def td_seq(self, asint: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def trix(
        self,
        length: Optional[int] = None,
        signal: Optional[int] = None,
        scalar: Optional[float] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def trixh(
        self,
        length: Optional[int] = None,
        signal: Optional[int] = None,
        scalar: Optional[float] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def tsi(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        signal: Optional[int] = None,
        scalar: Optional[float] = None,
        mamode: Optional[str] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def uo(
        self,
        fast: Optional[int] = None,
        medium: Optional[int] = None,
        slow: Optional[int] = None,
        fast_w: Optional[float] = None,
        medium_w: Optional[float] = None,
        slow_w: Optional[float] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def vwmacd(
        self, fast: Optional[int] = None, slow: Optional[int] = None, signal: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def willr(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...

    # overlap
    def alma(
        self,
        length: Optional[int] = None,
        sigma: Optional[float] = None,
        distribution_offset: Optional[float] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def avgprice(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def dema(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ema(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def fwma(self, length: Optional[int] = None, asc: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def hilo(
        self,
        high_length: Optional[int] = None,
        low_length: Optional[int] = None,
        mamode: Optional[str] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def hl2(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def hlc3(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def hma(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ht_trendline(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def hwma(
        self, na: Optional[float] = None, nb: Optional[float] = None, nc: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def ichimoku(
        self,
        tenkan: Optional[int] = None,
        kijun: Optional[int] = None,
        senkou: Optional[int] = None,
        include_chikou: bool = True,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> tuple[Optional[DataFrame], Optional[DataFrame]]: ...
    def jma(
        self, length: Optional[Union[int, float]] = None, phase: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def kama(
        self,
        length: Optional[int] = None,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def linreg(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def linregangle(
        self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def linregintercept(
        self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def linregslope(
        self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def ma(self, name: Optional[str] = None, source: Optional[Series] = None, **kwargs: Any) -> Optional[Series]: ...
    def mama(
        self,
        fastlimit: Optional[float] = None,
        slowlimit: Optional[float] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def mavp(
        self,
        periods: Optional[Series] = None,
        minperiod: Optional[int] = None,
        maxperiod: Optional[int] = None,
        mamode: Optional[int] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def mcgd(self, length: Optional[int] = None, offset: Optional[int] = None, c: Optional[float] = None, **kwargs: Any) -> Optional[Series]: ...
    def medprice(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def midpoint(
        self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def midprice(
        self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def mmar(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def ohlc4(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def pwma(self, length: Optional[int] = None, asc: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def rainbow(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def rma(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def sinwma(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def sma(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def ssf(self, length: Optional[int] = None, poles: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def supertrend(
        self, length: Optional[int] = None, multiplier: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def swma(self, length: Optional[int] = None, asc: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def t3(
        self, length: Optional[int] = None, a: Optional[float] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def tema(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def trima(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def tsf(self, length: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def typprice(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def vidya(self, length: Optional[int] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def vwap(self, anchor: Optional[str] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def vwma(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def wcp(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def wma(
        self, length: Optional[int] = None, asc: Optional[bool] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def zlma(self, length: Optional[int] = None, mamode: Optional[str] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...

    # performance
    def drawdown(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def log_return(
        self, length: Optional[int] = None, cumulative: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def percent_return(
        self, length: Optional[int] = None, cumulative: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...

    # statistics
    def beta(
        self, benchmark: Optional[Series] = None, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def correl(
        self, benchmark: Optional[Series] = None, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def entropy(
        self, length: Optional[int] = None, base: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def kurtosis(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def mad(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def md(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def median(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def quantile(self, length: Optional[int] = None, q: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def skew(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def stderr(self, length: Optional[int] = None, ddof: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def stdev(
        self, length: Optional[int] = None, ddof: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def tos_stdevall(
        self, length: Optional[int] = None, stds: Optional[list[int]] = None, ddof: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def variance(
        self, length: Optional[int] = None, ddof: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def zscore(self, length: Optional[int] = None, std: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...

    # trend
    def adx(
        self,
        length: Optional[int] = None,
        lensig: Optional[int] = None,
        scalar: Optional[float] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def adxr(
        self,
        length: Optional[int] = None,
        lensig: Optional[int] = None,
        scalar: Optional[float] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def amat(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        lookback: Optional[int] = None,
        mamode: Optional[str] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def aroon(
        self, length: Optional[int] = None, scalar: Optional[float] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def chop(
        self,
        length: Optional[int] = None,
        atr_length: Optional[int] = None,
        ln: Optional[bool] = None,
        scalar: Optional[float] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def cksp(
        self,
        p: Optional[int] = None,
        x: Optional[float] = None,
        q: Optional[int] = None,
        tvmode: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def cpr(
        self,
        open: Series,
        method: str = 'classic',
        timeframe: str = 'daily',
        interval: Optional[str] = None,
        levels: str = 'standard',
        width_analysis: bool = True,
        price_position: bool = True,
        virgin_cpr: bool = False,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def decay(
        self, kind: Optional[str] = None, length: Optional[int] = None, mode: Optional[str] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def decreasing(
        self,
        length: Optional[int] = None,
        strict: Optional[bool] = None,
        asint: Optional[bool] = None,
        percent: Optional[float] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def dpo(self, length: Optional[int] = None, centered: bool = True, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def dx(
        self,
        length: Optional[int] = None,
        scalar: Optional[float] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def edecay(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def increasing(
        self,
        length: Optional[int] = None,
        strict: Optional[bool] = None,
        asint: Optional[bool] = None,
        percent: Optional[float] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def long_run(self, fast: Series, slow: Series, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def minus_dm(
        self, length: Optional[int] = None, talib: Optional[bool] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def plus_dm(
        self, length: Optional[int] = None, talib: Optional[bool] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def pmax(
        self,
        length: Optional[int] = None,
        multiplier: Optional[float] = None,
        mamode: Optional[str] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def psar(
        self,
        af0: Optional[float] = None,
        af: Optional[float] = None,
        max_af: Optional[float] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def qstick(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def sarext(
        self,
        startvalue: Optional[float] = None,
        offsetonreverse: Optional[float] = None,
        accelerationinitlong: Optional[float] = None,
        accelerationlong: Optional[float] = None,
        accelerationmaxlong: Optional[float] = None,
        accelerationinitshort: Optional[float] = None,
        accelerationshort: Optional[float] = None,
        accelerationmaxshort: Optional[float] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def short_run(
        self, fast: Series, slow: Series, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def tsignals(
        self,
        trend: Series,
        asbool: Optional[bool] = None,
        trend_reset: int = 0,
        trade_offset: Optional[int] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def ttm_trend(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def vhf(self, length: Optional[int] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def vortex(
        self, length: Optional[int] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def xsignals(
        self,
        signal: Series,
        xa: float,
        xb: float,
        above: bool = True,
        long: bool = True,
        asbool: Optional[bool] = None,
        trend_reset: int = 0,
        trade_offset: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...

    # volatility
    def aberration(
        self, length: Optional[int] = None, atr_length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def accbands(
        self,
        length: Optional[int] = None,
        c: Optional[float] = None,
        drift: Optional[int] = None,
        mamode: Optional[str] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def atr(
        self,
        length: Optional[int] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def avolume(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def bbands(
        self,
        length: Optional[int] = None,
        std: Optional[float] = None,
        ddof: int = 0,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def ce(
        self,
        length: Optional[int] = None,
        multiplier: Optional[float] = None,
        mamode: Optional[str] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def cvi(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def donchian(
        self, lower_length: Optional[int] = None, upper_length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def hvol(
        self, length: Optional[int] = None, annualization: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def hwc(
        self,
        na: Optional[float] = None,
        nb: Optional[float] = None,
        nc: Optional[float] = None,
        nd: Optional[float] = None,
        scalar: Optional[float] = None,
        channel_eval: Optional[bool] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def kc(
        self, length: Optional[int] = None, scalar: Optional[float] = None, mamode: Optional[str] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[DataFrame]: ...
    def massi(self, fast: Optional[int] = None, slow: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def natr(
        self,
        length: Optional[int] = None,
        scalar: Optional[float] = None,
        mamode: Optional[str] = None,
        talib: Optional[bool] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def pdist(self, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def rvi(
        self,
        length: Optional[int] = None,
        scalar: Optional[float] = None,
        refined: Optional[bool] = None,
        thirds: Optional[bool] = None,
        mamode: Optional[str] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def thermo(
        self,
        length: Optional[int] = None,
        long: Optional[float] = None,
        short: Optional[float] = None,
        mamode: Optional[str] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def true_range(
        self, talib: Optional[bool] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def ui(self, length: Optional[int] = None, scalar: Optional[float] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...

    # volume
    def ad(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def adosc(
        self, fast: Optional[int] = None, slow: Optional[int] = None, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def aobv(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        max_lookback: Optional[int] = None,
        min_lookback: Optional[int] = None,
        mamode: Optional[str] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def cmf(self, length: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def efi(
        self, length: Optional[int] = None, mamode: Optional[str] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def emv(self, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def eom(
        self, length: Optional[int] = None, divisor: Optional[float] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def kvo(
        self,
        fast: Optional[int] = None,
        slow: Optional[int] = None,
        signal: Optional[int] = None,
        mamode: Optional[str] = None,
        drift: Optional[int] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[DataFrame]: ...
    def marketfi(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def mfi(
        self, length: Optional[int] = None, talib: Optional[bool] = None, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any
    ) -> Optional[Series]: ...
    def nvi(self, length: Optional[int] = None, initial: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def obv(self, talib: Optional[bool] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def pvi(self, length: Optional[int] = None, initial: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def pvol(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def pvr(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def pvt(self, drift: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def vfi(
        self,
        length: Optional[int] = None,
        coef: Optional[float] = None,
        vcoef: Optional[float] = None,
        mamode: Optional[str] = None,
        offset: Optional[int] = None,
        **kwargs: Any,
    ) -> Optional[Series]: ...
    def vosc(self, fast: Optional[int] = None, slow: Optional[int] = None, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
    def vp(self, width: Optional[int] = None, **kwargs: Any) -> Optional[DataFrame]: ...
    def wad(self, offset: Optional[int] = None, **kwargs: Any) -> Optional[Series]: ...
