from ._candles import candle_color
from ._core import (
    apply_fill,
    apply_offset,
    get_drift,
    get_offset,
    is_datetime_ordered,
    is_percent,
    non_zero_range,
    recent_maximum_index,
    recent_minimum_index,
    signed_series,
    tal_ma,
    unsigned_differences,
    verify_series,
)
from ._math import (
    combination,
    df_error_analysis,
    fibonacci,
    linear_regression,
    np_rolling_moments,
    pascals_triangle,
    symmetric_triangle,
    weights,
    zero,
)

# volatility is re-exported for utils.volatility() access but kept out of
# __all__ so it never shadows the pandas_ta_classic.volatility subpackage.
from ._metrics import (
    cagr,
    calmar_ratio,
    downside_deviation,
    jensens_alpha,
    log_max_drawdown,
    max_drawdown,
    optimal_leverage,
    pure_profit_score,
    sharpe_ratio,
    sortino_ratio,
    volatility as volatility,
)
from ._signals import (
    above,
    above_value,
    below,
    below_value,
    cross,
    cross_value,
    crossover,
    lag,
    signals,
)
from ._time import df_year_to_date, final_time, get_time, to_utc, total_time
from .data import av, yf

__all__ = [
    "above",
    "above_value",
    "apply_fill",
    "apply_offset",
    "av",
    "below",
    "below_value",
    "cagr",
    "calmar_ratio",
    "candle_color",
    "combination",
    "cross",
    "cross_value",
    "crossover",
    "df_error_analysis",
    "df_year_to_date",
    "downside_deviation",
    "fibonacci",
    "final_time",
    "get_drift",
    "get_offset",
    "get_time",
    "is_datetime_ordered",
    "is_percent",
    "jensens_alpha",
    "lag",
    "linear_regression",
    "log_max_drawdown",
    "max_drawdown",
    "non_zero_range",
    "np_rolling_moments",
    "optimal_leverage",
    "pascals_triangle",
    "pure_profit_score",
    "recent_maximum_index",
    "recent_minimum_index",
    "sharpe_ratio",
    "signals",
    "signed_series",
    "sortino_ratio",
    "symmetric_triangle",
    "tal_ma",
    "to_utc",
    "total_time",
    "unsigned_differences",
    "verify_series",
    "weights",
    "yf",
    "zero",
]
