#!/usr/bin/env python
"""Generate pandas_ta_classic/core.pyi from indicator function signatures."""

import inspect
import types
import typing
from pathlib import Path

from pandas_ta_classic._indicator_loader import (
    _COLUMN_PARAM_TO_COL_KEY,
    _find_indicator_func,
)
from pandas_ta_classic._meta import Category

ROOT = Path(__file__).parent.parent

_RETURN_MAP = {
    # The accessor always opts in to the single-DataFrame return internally
    # (as_dataframe=True is hardcoded in core.py); it never returns the tuple.
    "ichimoku": "DataFrame | None",
}

# Params the underlying indicator function accepts but the hand-written
# accessor wrapper in core.py does not expose (it hardcodes the value
# instead). Stubbing these would advertise a kwarg that raises
# "got multiple values" at runtime if a caller actually passes it.
_PARAM_EXCLUDE_MAP = {
    "ichimoku": {"as_dataframe"},
}


def _build_method_stub(name: str, func) -> str:
    sig = inspect.signature(func)
    excluded_params = _PARAM_EXCLUDE_MAP.get(name, frozenset())

    # Build param list: self + non-column params
    parts = ["self"]
    for pname, param in sig.parameters.items():
        if pname in _COLUMN_PARAM_TO_COL_KEY or pname in excluded_params:
            continue
        if param.kind == inspect.Parameter.VAR_KEYWORD:
            parts.append("**kwargs: Any")
        else:
            annotation = ""
            if param.annotation is not inspect.Parameter.empty:
                annotation = f": {_format_annotation(param.annotation)}"
            default = ""
            if param.default is not inspect.Parameter.empty:
                default = f" = {param.default!r}"
            parts.append(f"{pname}{annotation}{default}")

    # Return type
    ret = "Series | DataFrame | None"
    if name in _RETURN_MAP:
        ret = _RETURN_MAP[name]
    elif sig.return_annotation is not inspect.Parameter.empty:
        ret = _format_annotation(sig.return_annotation)

    params_str = ", ".join(parts)
    return f"    def {name}({params_str}) -> {ret}: ..."


_BARE_NAME_OVERRIDES = {
    "Series": "Series",
    "DataFrame": "DataFrame",
    "Sequence": "Sequence",
    "NoneType": "None",
}


def _format_annotation(ann) -> str:
    """Render an annotation as a canonical, Python-version-independent string.

    Reconstructs the stub form from the typing API (``get_origin`` /
    ``get_args``) instead of relying on ``str(ann)``, whose output changed
    between Python 3.13 and 3.14 (``Optional[int]`` -> ``int | None``,
    ``Series`` -> ``pandas.Series``). The reconstruction normalises:

    * ``Optional[X]``, ``Union[X, None]`` and ``X | None`` -> ``X | None``
    * ``Union[A, B, None]`` -> ``A | B | None`` (PEP 604, ``None`` last)
    * Any pandas Series / DataFrame fully-qualified name -> bare class
    * ``typing.Sequence`` and ``collections.abc.Sequence`` -> ``Sequence``
    """
    if ann is type(None):
        return "None"

    origin = typing.get_origin(ann)
    args = typing.get_args(ann)

    # Union / PEP 604 X | Y
    if origin is typing.Union or origin is types.UnionType:
        non_none = [a for a in args if a is not type(None)]
        members = [_format_annotation(a) for a in non_none]
        if len(non_none) < len(args):
            members.append("None")
        return " | ".join(members)

    # Generic alias (List[X], Tuple[X, Y], dict[K, V], ...)
    if origin is not None:
        origin_name = getattr(origin, "__name__", None) or str(origin).rsplit(".", 1)[-1]
        # typing aliases like typing.List/Tuple expose origin = list/tuple
        if origin_name in ("list", "tuple", "dict", "set", "frozenset", "type"):
            origin_str = origin_name
        else:
            origin_str = origin_name
        inner = ", ".join(_format_annotation(a) for a in args) if args else ""
        return f"{origin_str}[{inner}]" if inner else origin_str

    # Bare class
    name = getattr(ann, "__name__", None) or str(ann).replace("typing.", "")
    return _BARE_NAME_OVERRIDES.get(name, name)


def main():
    lines = [
        "# This file is auto-generated by tools/gen_core_stub.py — do not edit manually.",
        "from collections.abc import Sequence",
        "from typing import Any",
        "",
        "from pandas import DataFrame, Series",
        "",
        "class AnalysisIndicators:",
    ]

    for cat, indicators in sorted(Category.items()):
        lines.append(f"    # {cat}")
        for ind_name in sorted(indicators):
            func = _find_indicator_func(ind_name)
            if func is None:
                continue
            lines.append(_build_method_stub(ind_name, func))
        lines.append("")

    out_path = ROOT / "pandas_ta_classic" / "core.pyi"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    # The committed stub is black-formatted; run black afterwards or the
    # code-quality gate will flag the raw single-line output.
    print(f"Wrote {out_path} ({len(lines)} lines) — now run: black {out_path}")


if __name__ == "__main__":
    main()
