#!/usr/bin/env python
"""Generate pandas_ta_classic/core.pyi from indicator function signatures."""
import importlib
import inspect
import sys
from pathlib import Path

# Ensure the project root is on sys.path
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from pandas_ta_classic._meta import Category
from pandas_ta_classic._indicator_loader import (
    _find_indicator_func,
    _COLUMN_PARAM_TO_COL_KEY,
)

_RETURN_MAP = {
    "ichimoku": "tuple[Optional[DataFrame], Optional[DataFrame]]",
}


def _build_method_stub(name: str, func) -> str:
    sig = inspect.signature(func)

    # Build param list: self + non-column params
    parts = ["self"]
    for pname, param in sig.parameters.items():
        if pname in _COLUMN_PARAM_TO_COL_KEY:
            continue
        if param.kind == inspect.Parameter.VAR_KEYWORD:
            parts.append("**kwargs: Any")
        else:
            annotation = ""
            if param.annotation is not inspect.Parameter.empty:
                annotation = f": {_format_annotation(param.annotation)}"
            default = ""
            if param.default is not inspect.Parameter.empty:
                default = f" = {repr(param.default)}"
            parts.append(f"{pname}{annotation}{default}")

    # Return type
    ret = "Optional[Union[Series, DataFrame]]"
    if name in _RETURN_MAP:
        ret = _RETURN_MAP[name]
    elif sig.return_annotation is not inspect.Parameter.empty:
        ret = _format_annotation(sig.return_annotation)

    params_str = ", ".join(parts)
    return f"    def {name}({params_str}) -> {ret}: ..."


def _format_annotation(ann) -> str:
    if ann is type(None):
        return "None"
    if hasattr(ann, "__origin__"):
        raw = str(ann).replace("typing.", "")
        raw = raw.replace("pandas.core.series.Series", "Series")
        raw = raw.replace("pandas.core.frame.DataFrame", "DataFrame")
        raw = raw.replace("NoneType", "None")
        raw = raw.replace("collections.abc.Sequence", "Sequence")
        return raw
    name = getattr(ann, "__name__", None) or str(ann)
    # Normalise fully-qualified pandas names
    name = name.replace("pandas.core.series.Series", "Series")
    name = name.replace("pandas.core.frame.DataFrame", "DataFrame")
    return name


def main():
    lines = [
        "# This file is auto-generated by tools/gen_core_stub.py — do not edit manually.",
        "from typing import Any, Optional, Sequence, Union",
        "from pandas import Series, DataFrame",
        "",
        "class AnalysisIndicators:",
    ]

    for cat, indicators in sorted(Category.items()):
        lines.append(f"    # {cat}")
        for ind_name in sorted(indicators):
            func = _find_indicator_func(ind_name)
            if func is None:
                continue
            try:
                stub = _build_method_stub(ind_name, func)
                lines.append(stub)
            except Exception as e:
                lines.append(
                    f"    def {ind_name}(self, **kwargs: Any) -> Optional[Union[Series, DataFrame]]: ...  # stub-gen failed: {e}"
                )
        lines.append("")

    out_path = ROOT / "pandas_ta_classic" / "core.pyi"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
