#!/usr/bin/env python
"""Generate pandas_ta_classic/core.pyi from indicator function signatures."""

import inspect
import types
import typing
from pathlib import Path

from pandas_ta_classic._meta import Category
from pandas_ta_classic._indicator_loader import (
    _find_indicator_func,
    _COLUMN_PARAM_TO_COL_KEY,
)

# PEP 604 union type added in Python 3.10. Guard for back-compat.
_UNION_TYPE = getattr(types, "UnionType", None)

ROOT = Path(__file__).parent.parent

_RETURN_MAP = {
    "ichimoku": "tuple[Optional[DataFrame], Optional[DataFrame]]",
}


def _build_method_stub(name: str, func) -> str:
    sig = inspect.signature(func)

    # Build param list: self + non-column params
    parts = ["self"]
    for pname, param in sig.parameters.items():
        if pname in _COLUMN_PARAM_TO_COL_KEY:
            continue
        if param.kind == inspect.Parameter.VAR_KEYWORD:
            parts.append("**kwargs: Any")
        else:
            annotation = ""
            if param.annotation is not inspect.Parameter.empty:
                annotation = f": {_format_annotation(param.annotation)}"
            default = ""
            if param.default is not inspect.Parameter.empty:
                default = f" = {repr(param.default)}"
            parts.append(f"{pname}{annotation}{default}")

    # Return type
    ret = "Optional[Union[Series, DataFrame]]"
    if name in _RETURN_MAP:
        ret = _RETURN_MAP[name]
    elif sig.return_annotation is not inspect.Parameter.empty:
        ret = _format_annotation(sig.return_annotation)

    params_str = ", ".join(parts)
    return f"    def {name}({params_str}) -> {ret}: ..."


_BARE_NAME_OVERRIDES = {
    "Series": "Series",
    "DataFrame": "DataFrame",
    "Sequence": "Sequence",
    "NoneType": "None",
}


def _format_annotation(ann) -> str:
    """Render an annotation as a canonical, Python-version-independent string.

    Reconstructs the stub form from the typing API (``get_origin`` /
    ``get_args``) instead of relying on ``str(ann)``, whose output changed
    between Python 3.13 and 3.14 (``Optional[int]`` -> ``int | None``,
    ``Series`` -> ``pandas.Series``). The reconstruction normalises:

    * ``Union[X, None]`` and ``X | None`` -> ``Optional[X]``
    * ``Union[A, B, None]`` -> ``Optional[Union[A, B]]``
    * Any pandas Series / DataFrame fully-qualified name -> bare class
    * ``typing.Sequence`` and ``collections.abc.Sequence`` -> ``Sequence``
    """
    if ann is type(None):
        return "None"

    origin = typing.get_origin(ann)
    args = typing.get_args(ann)

    # Union / PEP 604 X | Y
    if origin is typing.Union or (_UNION_TYPE is not None and origin is _UNION_TYPE):
        non_none = [a for a in args if a is not type(None)]
        has_none = len(non_none) < len(args)
        if has_none and len(non_none) == 1:
            return f"Optional[{_format_annotation(non_none[0])}]"
        if has_none:
            inner = ", ".join(_format_annotation(a) for a in non_none)
            return f"Optional[Union[{inner}]]"
        inner = ", ".join(_format_annotation(a) for a in args)
        return f"Union[{inner}]"

    # Generic alias (List[X], Tuple[X, Y], dict[K, V], ...)
    if origin is not None:
        origin_name = getattr(origin, "__name__", None) or str(origin).rsplit(".", 1)[-1]
        # typing aliases like typing.List/Tuple expose origin = list/tuple
        if origin_name in ("list", "tuple", "dict", "set", "frozenset", "type"):
            origin_str = origin_name
        else:
            origin_str = origin_name
        inner = ", ".join(_format_annotation(a) for a in args) if args else ""
        return f"{origin_str}[{inner}]" if inner else origin_str

    # Bare class
    name = getattr(ann, "__name__", None) or str(ann).replace("typing.", "")
    return _BARE_NAME_OVERRIDES.get(name, name)


def main():
    lines = [
        "# This file is auto-generated by tools/gen_core_stub.py — do not edit manually.",
        "from typing import Any, Optional, Sequence, Union",
        "from pandas import Series, DataFrame",
        "",
        "class AnalysisIndicators:",
    ]

    for cat, indicators in sorted(Category.items()):
        lines.append(f"    # {cat}")
        for ind_name in sorted(indicators):
            func = _find_indicator_func(ind_name)
            if func is None:
                continue
            try:
                stub = _build_method_stub(ind_name, func)
                lines.append(stub)
            except Exception as e:
                lines.append(f"    def {ind_name}(self, **kwargs: Any) -> Optional[Union[Series, DataFrame]]: ...  # stub-gen failed: {e}")
        lines.append("")

    out_path = ROOT / "pandas_ta_classic" / "core.pyi"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    # The committed stub is black-formatted; run black afterwards or the
    # code-quality gate will flag the raw single-line output.
    print(f"Wrote {out_path} ({len(lines)} lines) — now run: black {out_path}")


if __name__ == "__main__":
    main()
